apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: suanx/gfx:latest
          name: c1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: srvc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80            # Exposes service on port 80
      targetPort: 80       # Connects to containerPort 80
      protocol: TCP
      nodePort: 30350      # External access via NodePort
