pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'suanx/webdeck'
        EC2_IP = '54.210.59.213'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/suanx/devops-ci-cd-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE project2/' // Adjust path if needed
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-dock', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGE
                        '''
                    }
                }
            }
        }

                stage('Deploy to EC2') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-ec2', keyFileVariable: 'instanceconn')]) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no -i "$instanceconn" ec2-user@$EC2_IP "
                    sudo docker stop webdeck || true &&
                    sudo docker pull $DOCKER_IMAGE &&
                    sudo docker run -d -p 80:80 --name webdeck $DOCKER_IMAGE
                    "
                    '''
                }
            }
        }

    }
}
