pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'suanx/webdeck'
        EC2_IP = '54.210.59.213'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/suanx/devops-ci-cd-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'ls -l project2'  // Check if Dockerfile exists
                sh 'docker build -t $DOCKER_IMAGE -f project2/Dockerfile project2/'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-dock', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $DOCKER_IMAGE
                    docker logout
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-ec2', keyFileVariable: 'EC2_KEY', usernameVariable: 'EC2_USER')]) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_IP "
                    docker stop webdeck || true &&
                    docker pull $DOCKER_IMAGE &&
                    docker run -d -p 80:80 --name webdeck $DOCKER_IMAGE
                    "
                    '''
                }
            }
        }
    }
}
