pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'suanx/webdeck'
        EC2_IP = '54.210.59.213'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/suanx/devops-ci-cd-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-dock', passwordVariable: 'jenkinstoredusrpass', usernameVariable: 'jenkinstoredusrname')]) {
                    sh '''
                    docker login -u $jenkinstoredusrname -p $jenkinstoredusrpass
                    docker push $DOCKER_IMAGE
                    docker logout
                    '''
                }
            }
        }

        stage('Deploy on EC2') {
            steps {
                sshagent(['jenkins-ec2']) {
                    sh '''
                    ssh ec2-user@$EC2_IP "
                    docker stop myapp || true &&
                    docker pull $DOCKER_IMAGE &&
                    docker run -d -p 80:80 --name myapp $DOCKER_IMAGE
                    "
                    '''
                }
            }
        }
    }
}
